defmodule Shardex do
  @moduledoc """
  Route keys and batches of items to sharded pools.

  Define an instance:

      defmodule MyApp.Shards do
        use Shardex, otp_app: :my_app
      end

      # config/runtime.exs
      config :my_app, MyApp.Shards,
        shards: [
          shard_1: [
            primary: {Shardex.Adapter.Ecto, repo: MyApp.Repo, config: [database: "s1"]},
            replica: {Shardex.Adapter.Ecto, repo: MyApp.Repo, config: [database: "s1_ro"]}
          ],
          shard_2: {Shardex.Adapter.Ecto, repo: MyApp.Repo, config: [database: "s2"]}
        ]

  Add `MyApp.Shards` to your supervision tree, then:

      MyApp.Shards.run(org_id, fn repo -> repo.all(Contact) end)
      MyApp.Shards.run_batch(messages, & &1.org_id, fn repo, msgs -> insert_all(repo, msgs) end)

  Every function generated by `use Shardex` delegates to the function of the
  same name in this module with the instance as first argument.
  """

  alias Shardex.Coordinator
  alias Shardex.Names
  alias Shardex.Router
  alias Shardex.State
  alias Shardex.Strategy.Cached

  @typedoc "Reason returned in `{:error, reason}` by the routing functions."
  @type reason ::
          :maintenance
          | :unassigned
          | :no_routable_shards
          | {:unknown_shard, term()}
          | {:unknown_role, atom()}
          | {:strategy_error, term()}
          | term()

  @typedoc "An instance: the `use Shardex` module or the `:name` given to `start_link/1`."
  @type instance :: atom()

  @doc """
  Starts an instance. Usually you `use Shardex` instead and add your module to
  your supervision tree.

  ## Options

  #{NimbleOptions.docs(Shardex.Config.schema())}
  """
  @spec start_link(keyword()) :: Supervisor.on_start()
  def start_link(opts), do: Shardex.Supervisor.start_link(opts)

  @doc """
  Returns the shard a key routes to.

  Errors: `:unassigned`, `:maintenance`, `:no_routable_shards`,
  `{:unknown_shard, name}`, `{:strategy_error, value}` or any `{:error, term}`
  returned by your strategy.
  """
  @spec lookup(instance(), term(), keyword()) :: {:ok, Shardex.Shard.t()} | {:error, reason()}
  def lookup(instance, key, opts \\ []), do: Router.lookup(instance, key, opts)

  @doc """
  Returns the ref of the pool a key routes to.

  ## Options

    * `:role` - pool role (default `:primary`)
    * `:fallback` - role or list of roles to try, in order, when `:role` is missing
      or in maintenance
  """
  @spec ref(instance(), term(), keyword()) :: {:ok, term()} | {:error, reason()}
  def ref(instance, key, opts \\ []), do: Router.ref(instance, key, opts)

  @doc "Like `ref/3` but raises `Shardex.Error`."
  @spec ref!(instance(), term(), keyword()) :: term()
  def ref!(instance, key, opts \\ []), do: Router.ref!(instance, key, opts)

  @doc """
  Runs `fun` against the pool a key routes to, inside the adapter's context
  (for Ecto dynamic repos, `put_dynamic_repo/1` is set and restored).

  Accepts the same options as `ref/3`. Exceptions raised by `fun` propagate;
  nothing is retried.
  """
  @spec run(instance(), term(), (term() -> result), keyword()) :: {:ok, result} | {:error, reason()}
        when result: term()
  def run(instance, key, fun, opts \\ []), do: Router.run(instance, key, fun, opts)

  @doc "Like `run/4` but returns the result directly and raises `Shardex.Error` on routing errors."
  @spec run!(instance(), term(), (term() -> result), keyword()) :: result when result: term()
  def run!(instance, key, fun, opts \\ []), do: Router.run!(instance, key, fun, opts)

  @doc """
  Groups items by the shard their key routes to, calling the strategy once with
  the deduplicated keys. Every item ends up exactly once in either a group or
  `errors`. Accepts `:role` and `:fallback` like `ref/3`; items whose shard has
  no usable role go to `errors`.
  """
  @spec group(instance(), Enumerable.t(), (term() -> term()), keyword()) :: Shardex.Batch.t()
  def group(instance, items, key_fun, opts \\ []), do: Router.group(instance, items, key_fun, opts)

  @doc """
  Groups items (see `group/4`) and calls `fun.(ref, items)` once per shard,
  inside the adapter's context. Returns `{:ok, %{shard => result}, errors}`.

  ## Options

    * `:role`, `:fallback` - as in `ref/3`
    * `:on_error` - `:collect` (default) or `:raise` (raise `Shardex.BatchError`
      before running anything if any item cannot be routed)
    * `:max_concurrency` - run up to N shard groups in parallel tasks (default 1)
    * `:timeout` - per-group timeout when `max_concurrency > 1` (default `:infinity`)
  """
  @spec run_batch(instance(), Enumerable.t(), (term() -> term()), (term(), [term()] -> result), keyword()) ::
          {:ok, %{atom() => result}, [{term(), reason()}]}
        when result: term()
  def run_batch(instance, items, key_fun, fun, opts \\ []), do: Router.run_batch(instance, items, key_fun, fun, opts)

  @doc """
  Takes a shard (or one of its roles with `role:`) out of rotation.

    * `:drain` - stop routing to it; pools keep running
    * `:stop` - stop routing to it, then stop its pools

  Idempotent. Hash strategies keep routing over the full shard list, so keys of a
  shard in maintenance get `{:error, :maintenance}` rather than moving elsewhere.
  """
  @spec maintenance(instance(), atom(), :drain | :stop, keyword()) :: :ok | {:error, term()}
  def maintenance(instance, shard, mode, opts \\ []) when mode in [:drain, :stop] do
    target = if mode == :stop, do: :stopped, else: :drain
    Coordinator.call(instance, {:set_status, shard, Keyword.get(opts, :role), target})
  end

  @doc """
  Puts a shard (or one role with `role:`) back into rotation, starting pools
  first. Without `role:`, every role of the shard becomes active. Idempotent.
  """
  @spec activate(instance(), atom(), keyword()) :: :ok | {:error, term()}
  def activate(instance, shard, opts \\ []) do
    Coordinator.call(instance, {:set_status, shard, Keyword.get(opts, :role), :active})
  end

  @doc "Returns the status of a shard and of each of its roles."
  @spec status(instance(), atom()) ::
          {:ok, %{status: Shardex.Shard.status(), roles: %{atom() => Shardex.Shard.status()}}}
          | {:error, {:unknown_shard, atom()}}
  def status(instance, shard) do
    case State.fetch_shard(instance, shard) do
      {:ok, shard} -> {:ok, %{status: shard.status, roles: Map.new(shard.roles, fn {r, p} -> {r, p.status} end)}}
      :error -> {:error, {:unknown_shard, shard}}
    end
  end

  @doc "Lists shards in configuration order. `meta.pids` maps each role to its pool pid (or `nil`)."
  @spec shards(instance()) :: [Shardex.Shard.t()]
  def shards(instance) do
    topology = State.topology!(instance)

    pids =
      for {id, pid, _type, _mods} <- Supervisor.which_children(Names.pool_sup(instance)), is_pid(pid), into: %{} do
        {id, pid}
      end

    for name <- topology.shards, {:ok, shard} <- [State.fetch_shard(instance, name)] do
      role_pids = Map.new(shard.roles, fn {role, _pool} -> {role, Map.get(pids, {name, role})} end)
      %{shard | meta: Map.put(shard.meta, :pids, role_pids)}
    end
  end

  @doc false
  @spec child_spec(keyword()) :: Supervisor.child_spec()
  def child_spec(opts) do
    %{id: Keyword.get(opts, :name, __MODULE__), start: {__MODULE__, :start_link, [opts]}, type: :supervisor}
  end

  @doc """
  Adds a shard at runtime: initializes its adapters, starts its pools, then
  makes it routable (or leaves it drained with `status: :drain`).

  Runtime changes are kept in memory only; after a restart the boot config wins.
  With `Shardex.Strategy.Hash` most keys remap; with `JumpHash` ~1/n keys move
  to the new shard.
  """
  @spec add_shard(instance(), atom(), term(), keyword()) :: :ok | {:error, term()}
  def add_shard(instance, name, spec, opts \\ []) when is_atom(name) do
    status = Keyword.get(opts, :status, :active)

    if status not in [:active, :drain] do
      raise ArgumentError, "expected :status to be :active or :drain, got: #{inspect(status)}"
    end

    Coordinator.call(instance, {:add_shard, name, spec, status})
  end

  @doc "Removes a shard at runtime: unroutes it, stops its pools and drops it from the strategy."
  @spec remove_shard(instance(), atom()) :: :ok | {:error, {:unknown_shard, atom()} | :last_shard}
  def remove_shard(instance, name), do: Coordinator.call(instance, {:remove_shard, name})

  @doc """
  Drops a cached routing entry (or `:all`) when the instance uses
  `Shardex.Strategy.Cached`. Returns `{:error, :not_cached}` otherwise.
  """
  @spec invalidate(instance(), term()) :: :ok | {:error, :not_cached}
  def invalidate(instance, key) do
    case State.topology!(instance) do
      %{strategy: Cached, strategy_state: state} -> Cached.invalidate(state, key)
      _topology -> {:error, :not_cached}
    end
  end

  @doc """
  Defines an instance module. Its functions mirror the ones in `Shardex`
  without the instance argument.

  Options:

    * `:otp_app` (required) - the application whose config holds the
      instance's options under `config otp_app, MyModule, ...`
  """
  defmacro __using__(opts) do
    otp_app = Keyword.fetch!(opts, :otp_app)

    quote bind_quoted: [otp_app: otp_app] do
      @shardex_otp_app otp_app

      @doc false
      def child_spec(opts), do: %{id: __MODULE__, start: {__MODULE__, :start_link, [opts]}, type: :supervisor}

      @doc """
      Starts the instance. `opts` are merged over the `#{inspect(@shardex_otp_app)}`
      application config for `#{inspect(__MODULE__)}`. See `Shardex.start_link/1`.
      """
      def start_link(opts \\ []) do
        @shardex_otp_app
        |> Application.get_env(__MODULE__, [])
        |> Keyword.merge(opts)
        |> Keyword.put(:name, __MODULE__)
        |> Shardex.start_link()
      end

      @doc "See `Shardex.lookup/3`."
      def lookup(key, opts \\ []), do: Shardex.lookup(__MODULE__, key, opts)
      @doc "See `Shardex.ref/3`."
      def ref(key, opts \\ []), do: Shardex.ref(__MODULE__, key, opts)
      @doc "See `Shardex.ref!/3`."
      def ref!(key, opts \\ []), do: Shardex.ref!(__MODULE__, key, opts)
      @doc "See `Shardex.run/4`."
      def run(key, fun, opts \\ []), do: Shardex.run(__MODULE__, key, fun, opts)
      @doc "See `Shardex.run!/4`."
      def run!(key, fun, opts \\ []), do: Shardex.run!(__MODULE__, key, fun, opts)
      @doc "See `Shardex.group/4`."
      def group(items, key_fun, opts \\ []), do: Shardex.group(__MODULE__, items, key_fun, opts)
      @doc "See `Shardex.run_batch/5`."
      def run_batch(items, key_fun, fun, opts \\ []), do: Shardex.run_batch(__MODULE__, items, key_fun, fun, opts)
      @doc "See `Shardex.maintenance/4`."
      def maintenance(shard, mode, opts \\ []), do: Shardex.maintenance(__MODULE__, shard, mode, opts)
      @doc "See `Shardex.activate/3`."
      def activate(shard, opts \\ []), do: Shardex.activate(__MODULE__, shard, opts)
      @doc "See `Shardex.status/2`."
      def status(shard), do: Shardex.status(__MODULE__, shard)
      @doc "See `Shardex.shards/1`."
      def shards, do: Shardex.shards(__MODULE__)
      @doc "See `Shardex.add_shard/4`."
      def add_shard(name, spec, opts \\ []), do: Shardex.add_shard(__MODULE__, name, spec, opts)
      @doc "See `Shardex.remove_shard/2`."
      def remove_shard(name), do: Shardex.remove_shard(__MODULE__, name)
      @doc "See `Shardex.invalidate/2`."
      def invalidate(key), do: Shardex.invalidate(__MODULE__, key)
    end
  end
end
